# Generated by Django 2.0.5 on 2018-06-18 22:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escolas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=255)),
                ('cidade_escola', models.CharField(max_length=255)),
                ('uf_escola', models.CharField(max_length=14)),
                ('ensino_fundamental', models.PositiveIntegerField(default=0)),
                ('ensino_medio', models.PositiveIntegerField(default=0)),
                ('ensino_infantil', models.PositiveIntegerField(default=0)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
