# Generated by Django 3.1.7 on 2021-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mochilistas', '0002_auto_20210303_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escolas',
            name='tempo_de_servico',
        ),
        migrations.AlterField(
            model_name='escolas',
            name='ensino_fundamental',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='ensino_medio',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='ensino_infantil',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='uf_escola',
            field=models.CharField(max_length=2),
        ),
    ]
