# Generated by Django 3.1.7 on 2021-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mochilistas', '0003_auto_20210304_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolas',
            name='vagas_fundamental',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='escolas',
            name='vagas_infantil',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='escolas',
            name='vagas_medio',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
