# Generated by Django 3.1.7 on 2021-03-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mochilistas', '0004_auto_20210306_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolas',
            name='ensino_fundamental',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='ensino_infantil',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='ensino_medio',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='vagas_fundamental',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='vagas_infantil',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='escolas',
            name='vagas_medio',
            field=models.IntegerField(default=0),
        ),
    ]
