# Generated by Django 3.1.7 on 2021-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mochilistas', '0005_auto_20210306_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_aluno', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('data_nascimento_aluno', models.DateField()),
                ('email_aluno', models.CharField(max_length=100)),
                ('cidade_aluno', models.CharField(max_length=100)),
                ('uf_aluno', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='escolas',
            name='bairro_escola',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escolas',
            name='endereco_escola',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
