# Generated by Django 3.1.7 on 2021-03-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mochilistas', '0006_auto_20210306_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='data_nascimento_aluno',
        ),
        migrations.AlterField(
            model_name='alunos',
            name='id_aluno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
